### ISSUE TITLE
Deployment stuck on bridge creating

### ISSUE THREAD

**Issue by redixin** [CSSCorp/openstack-automation#4]
Here almost default config file: http://paste.ubuntu.com/7125446/
Here is venus ps axf: http://paste.ubuntu.com/7125460/
Here is mercury ps axf: http://paste.ubuntu.com/7125464/

I tried to add one more tunnel, and it freezes too:

 $ sudo ovs-vsctl add-br br-int1

Both venus and mercury are vm's with fresh Ubuntu-12.04.4

**Comment by Akilesh1597** [comment]
Thank you for your response. You have chosen vlan mode in your pillar file but mention about tunnel. This confuses me. However the issue is completely different.

Openvswitch seems to have some issues with i386 kernel and specifically those running on vm.
I am really sorry I was totally unable to deal with it. As you say ovs-vsctl add-br/add-port does not return. But if you terminate the command and do ovs-vsctl show, you will see that the bridge is already created. Salt-minion however will keep waiting for ovs-vsctl to exit. 

We have two options as of now. Use 64 bit kernel or remove the section corresponding to bridge addition from the formula neutron/openvswitch.sls, then do the process manually. Below is the part responsible for configuring bridges. If you are able to track the issue with openvswitch and 32 bit kernel you are welcome and please update me too.

<pre>
    "create_init_bridges": {
        "module": [
            "run",
            {
                "name": "cluster_ops.create_init_bridges"
            },
            {
                "require": [
                    {
                        "service": "openvswitch-switch"
                    }
                ]
            }
        ]
    }
</pre>

**Comment by Akilesh1597** [comment]
If you are not sure how to configure bridge manually here you go for your pillar file the series of command on mercury will be
ovs-vsctl add-br br-int
ovs-vsctl add-br br-eth1
ovs-vsctl add-port br-eth1 eth1
ovs-vsctl add-br br-ex
ovs-vsctl add-port br-ex eth2

for venus
ovs-vsctl add-br br-int
ovs-vsctl add-br br-eth1
ovs-vsctl add-port br-eth1 eth1

you would have to hit ctrl+c at the end of each command to exit. Then at the end verify if all went correct using ovs-vsctl show.

Then restart neutron-openvswitch-plugin-agent

Do come back if you have issues though

**Comment by redixin** [comment]
> You have chosen vlan mode in your pillar file but mention about tunnel.

Configuration with tunnel mode does not compile at all. I'll try it again later.

After killing ovs-vstl proceesess deployment were completed, but I cant figure out which password to use for horizon dashboard.

> Openvswitch seems to have some issues with i386 kernel and specifically those running on vm

Linux mercury 3.2.0-60-virtual #91-Ubuntu SMP Wed Feb 19 04:13:28 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Akilesh1597** [comment]
you have to use the account you created under the admin tenant. So that would be admin and admin_pass. See below part of the pillar.

<pre>
        "tenants": {
            "admin": {
                "users": {
                    "admin": {
                        "password": "admin_pass", 
                        "role": "admin", 
                        "email": "salt@csscorp.com"
                    }
                }
            }
      }
</pre>

And your kernel seems to be 64 bit but you still facing the issue. Beats me. 

Anyway has your bridges been created. If not please create them manually else the neutron ovs agent would not start. 

Meanwhile let me go back and see what can be done with ovs-vsctl. Surely its an openvswitch bug. But It does not occur on all systems and should have a workaround.

And please post me the error when you use gre mode. It should be some json syntax error.

**Comment by Akilesh1597** [comment]
Got information from openvswitch mailing list that ovs-vsctl waits for ovs-vswitchd to confirm creating of bridges. If ovs-vswitchd does not run in the machine it does not return. Fix added using --no-wait parameter for ovs-vsctl commands in create_init_bridges method. Alternatively ovs-vswitchd can be manually started in the machine using 'nohup ovs-vswitchd &'.
